POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "genZbuddha",
    "name": "supersuperuser",
    "password": "salainen"
}

###
GET http://localhost:3001/api/users